import 'branch.dart';
import 'subject.dart';

const DUMMY_BRANCHES = const [
  Branch(id: 'b1', name: "IT"),
  Branch(id: 'b2', name: "CSE"),
  Branch(id: 'b3', name: "CIVIL"),
  Branch(id: 'b4', name: "MECH"),
  Branch(id: 'b5', name: "AUTO"),
  Branch(id: 'b6', name: "EEE"),
  Branch(id: 'b7', name: "ECE"),
];

const DUMMY_SUBJECTS = const [
  Subject(
    branchID: 'b1',
    semester: 1,
    subjectID: 'b1sem1sub1',
    subjectName: 'B1Sem1SubjectName1',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b1',
    semester: 1,
    subjectID: 'b1sem1sub2',
    subjectName: 'B1Sem1SubjectName2',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b1',
    semester: 1,
    subjectID: 'b1sem1sub3',
    subjectName: 'B1Sem1SubjectName3',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b1',
    semester: 2,
    subjectID: 'b1sem2sub1',
    subjectName: 'B1Sem2SubjectName1',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b1',
    semester: 2,
    subjectID: 'b1sem2sub2',
    subjectName: 'B1Sem2SubjectName2',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b1',
    semester: 2,
    subjectID: 'b1sem2sub3',
    subjectName: 'B1Sem2SubjectName3',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b2',
    semester: 1,
    subjectID: 'b2sem1sub1',
    subjectName: 'B2Sem1SubjectName1',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b2',
    semester: 1,
    subjectID: 'b2sem1sub2',
    subjectName: 'B2Sem1SubjectName2',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b2',
    semester: 1,
    subjectID: 'b2sem1sub3',
    subjectName: 'B2Sem1SubjectName3',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b2',
    semester: 2,
    subjectID: 'b2sem2sub1',
    subjectName: 'B2Sem2SubjectName1',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b2',
    semester: 2,
    subjectID: 'b2sem2sub2',
    subjectName: 'B2Sem2SubjectName2',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  ),
  Subject(
    branchID: 'b2',
    semester: 2,
    subjectID: 'b2sem2sub3',
    subjectName: 'B2Sem2SubjectName3',
    subjectNotes: [
      "Unit-1.pdf",
      "Unit-2.pdf",
      "Unit-3.pdf",
      "Unit-4.pdf",
      "Unit-5.pdf",
    ],
  )
];
